const randomNames = [
    "Liam Carter",
    "Ava Morgan",
    "Noah Bennett",
    "Emma Clarke",
    "Mason Turner",
    "Sophia Hayes",
    "Lucas Griffin",
    "Isabella Brooks",
    "Ethan Parker",
    "Mia Sullivan",
    "Oliver Dawson",
    "Harper Lane",
    "Elijah Porter",
    "Chloe Mitchell",
    "James Rowan",
    "Lily Chandler",
    "Aiden Holt",
    "Grace Dalton",
    "Logan Barrett",
    "Ella Monroe",
    "Caleb Foster",
    "Nora Whitman",
    "Henry Collins",
    "Aria Preston",
    "Samuel Reed",
    "Zoe Hartman",
    "Nathan Pierce",
    "Maya Sinclair",
    "Gabriel Lyons",
    "Leah Everett",
    "Julian Cross",
    "Ruby Palmer",
    "Adrian Blake",
    "Stella Rivers",
    "Isaac Cooper",
    "Violet Ramsey",
    "Miles Archer",
    "Hazel Quinn",
    "Roman Ellis",
    "Clara Sutton",
    "Theo Maddox",
    "Ivy Chandler",
    "Sebastian Knox",
    "Audrey Lane",
    "Maxwell Thornton",
    "Penelope Shaw",
    "Dominic Hale",
    "Eliza Warren",
    "Weston Ford",
    "Juliette Marks"
]
const randomMessages = [
    "Hey, how are you?",
    "I'm good, how about you?",
    "Doing fine, thanks for asking!",
    "What are you up to today?",
    "Not much, just relaxing.",
    "Same here, taking it easy.",
    "Did you finish your project?",
    "Yeah, I wrapped it up last night.",
    "Nice, how did it turn out?",
    "Pretty good! I'm happy with it.",
    "Anyone here watched the new movie?",
    "Yeah, I saw it yesterday.",
    "How was it?",
    "It was amazing!",
    "I thought it was okay, not great.",
    "What didn't you like about it?",
    "The pacing felt slow.",
    "Oh really? I actually liked the pacing.",
    "Different tastes I guess!",
    "Absolutely, that's normal.",
    "Did you have breakfast yet?",
    "Not yet, still deciding what to eat.",
    "You should try oatmeal, it's great.",
    "I might actually do that!",
    "Hey everyone, what's going on?",
    "Just chatting about breakfast options.",
    "Nice, I'm having coffee right now.",
    "Black or with sugar?",
    "Black, always.",
    "Too strong for me!",
    "What are your weekend plans?",
    "Probably going hiking.",
    "Sounds fun, where?",
    "There's a trail near my house.",
    "I love that trail, it's beautiful!",
    "Have you guys seen the news today?",
    "No, what happened?",
    "Nothing major, just some weather updates.",
    "Oh, that's good.",
    "Is it going to rain?",
    "Looks like it, later tonight.",
    "Great, I love rain!",
    "I prefer sunny days.",
    "Same here, rainy weather makes me sleepy.",
    "Do you play any games?",
    "Yeah, mostly strategy games.",
    "Cool, any recommendations?",
    "Try 'Galaxy Conqueror', it's awesome.",
    "I’ve played that, it’s fun.",
    "What level are you on?",
    "Somewhere around level 18.",
    "Nice, I'm level 25!",
    "Whoa, you're ahead!",
    "How long did it take you?",
    "A few weeks.",
    "Do you guys read books?",
    "Yeah, I love sci-fi novels.",
    "Me too! Any favorites?",
    "Dune is my all-time favorite.",
    "That's a great choice.",
    "I haven’t read it yet.",
    "You should, it's fantastic.",
    "What's everyone working on right now?",
    "Just doing some chores.",
    "I'm finishing homework.",
    "Good luck with that!",
    "Thanks, I’ll need it.",
    "Anyone hungry?",
    "A little bit, yeah.",
    "I'm starving actually.",
    "Order something!",
    "What should I get?",
    "Pizza is always a good idea.",
    "True, can't go wrong with pizza.",
    "Does anyone cook here?",
    "Yeah, I cook pretty often.",
    "What's your favorite dish to make?",
    "Probably pasta.",
    "Pasta is awesome!",
    "Agreed!",
    "Has anyone traveled recently?",
    "Not recently, but planning a trip soon.",
    "Where to?",
    "Probably Japan.",
    "Nice, I’ve always wanted to go there.",
    "Same! The food must be amazing.",
    "Do you like anime?",
    "A little, not too much.",
    "I love anime!",
    "Which one is your favorite?",
    "Fullmetal Alchemist for sure.",
    "Great choice!",
    "Anyone here exercise regularly?",
    "Yeah, I go jogging.",
    "I try to go to the gym.",
    "I'm too lazy to exercise sometimes.",
    "Same, motivation is hard.",
    "How do you stay motivated?",
    "Music helps a lot.",
    "I should try that.",
    "What kind of music do you guys like?",
    "Mostly pop and rock.",
    "I listen to lo-fi a lot.",
    "Lo-fi is great for relaxing.",
    "Anyone learning something new?",
    "I'm learning guitar.",
    "That's awesome!",
    "How long have you been learning?",
    "About two months.",
    "Keep going, it gets easier!",
    "Thanks, I will.",
    "Is it cold where you guys are?",
    "Yeah, freezing!",
    "It's actually warm here.",
    "Lucky you!",
    "Anyone want to play a game later?",
    "Sure, I'm in.",
    "What game are we playing?",
    "Maybe trivia?",
    "Trivia sounds fun!",
    "Count me in too.",
    "Did you sleep well last night?",
    "Not really, I went to bed late.",
    "Same, couldn’t fall asleep.",
    "I slept great actually.",
    "Good for you!",
    "What time do you guys usually wake up?",
    "Around 7 AM.",
    "I get up at 9.",
    "I wake up whenever I want.",
    "Must be nice!",
    "Anyone have pets?",
    "Yeah, I have a dog.",
    "Cute! What’s its name?",
    "Max.",
    "I have a cat named Luna.",
    "Luna is a nice name!",
    "Thanks!",
    "What are you guys doing later?",
    "Probably watching a show.",
    "Which one?",
    "Maybe Stranger Things.",
    "Good choice!",
    "Has season 5 been good?",
    "Yes, very!",
    "Awesome, can’t wait to watch it.",
    "I'm just going to relax later.",
    "Same here."
]



export const getRandomMessage=()=>{
    const name = Math.floor(Math.random() * 50)
    const message = Math.floor(Math.random() * 150)
    return randomNames[name]+" "+ randomMessages[message]
    
}
console.log(getRandomMessage())